
# ä½œè€…ä¿¡æ¯
boy:
  name: é»‘çŸ³ #ç”·ç”Ÿæ˜µç§°
  avatar:
girl:
  name: å°ç‡• #å¥³ç”Ÿæ˜µç§°
  avatar:

#å¯¼èˆªæ¡
menu:
  ğŸš©é¦–é¡µ: /
  ğŸ’æƒ…ä¾£å“”å“”: https://www.heson10.com/lovebb



# å“”å“”è®¾ç½® â˜†å¿…é¡»
#ç”·ç”Ÿçš„å“”å“”
boybb:
  appId: 0KzOX4vC7Jsk6vzUGNeEiUaI-gzGzoHsz
  appKey: HwCiWuxfpvKiLm4teCUgTIba
  serverUrl: https://bbapi.heson10.com

#å¥³ç”Ÿçš„å“”å“”
girlbb:
  appId: 3ESXk94AEyyC1UiW314gQQz1-gzGzoHsz
  appKey: x76rfLe86pJxt2Tlzs3a67q6
  serverUrl: https://xfbb.heson10.com


# ç›¸æ‹çºªå¿µæ—¥
anniversary: '2015-06-30'

# ç™¾åº¦ç»Ÿè®¡
baidu_analytics_key: # 5fb5fd0062e816d3a3ca2dacf095bc0f 